# podinfo.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: team1
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*2.1
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
  values:
    image:
      repository: stefanprodan/podinfo
